### PR TITLE
fix: suggestions to spaces PR

### PR DESCRIPTION
**Pull request by oesteban**

### CODE REVIEW

**Comment by mgxd** [comment]
One thing to keep in mind as we move forward on this: since working on poldracklab/fmriprep#1915, I've realized we'll either have to rework `KeySelect` or move away from it, since we'll now support multiple specifications of the same templates.

**Comment by effigies** [comment]
@mgxd I made a comment to this effect in https://github.com/poldracklab/fmriprep/pull/1932#issuecomment-574191724. WDYT?

**Comment by oesteban** [comment]
This would need to happen in #1915. The way both outputs are generated ensures the keys and values to keyselect are in sync.

Plus, I think deferring this fix to #1915 just adds another failure point to an already complex change.

Maybe @soichih could test this fix and confirm it works?

My fear going the easy way is that the fix currently in #1932 does not ensure the synchronization between keys and fields.

**Comment by effigies** [comment]
Okay. Reading through this again, I think I'm fine with it. Let me re-run my test that replicated @soichih's issue with this branch, and I'll merge.

**Pull request merged**
